export const PATHAO_LOCATIONS = [
    "Aanbukhaireni / Abhukhaireni / Abhukhaireni",
    "Aanbukhaireni / Haramtari (Abhukhaireni) / Haramtari (Abhukhaireni)",
    "Aanbukhaireni / Palungtar (Abhukhaireni) / Palungtar (Abhukhaireni)",
    "Adarshanagar (Chitwan) / Adarshanagar (Chitwan) / Adarshanagar (Chitwan)",
    "Amargadi (Dadeldhura) / Amargadi (Dadeldhura) / Amargadi (Dadeldhura)",
    "Amlekhganj (Bara) / Amlekhganj (Bara) / Amlekhganj (Bara)",
    "Arghakhanchi / Arghakhanchi / Arghakhanchi",
    "Arnaha (Saptari) / Arnaha (Saptari) / Arnaha (Saptari)",
    "Arya Bhanjyang (Palpa) / Arya Bhanjyang (Palpa) / Arya Bhanjyang (Palpa)",
    "Attariya (Kailali) / Attariya (Kailali) / Attariya (Kailali)",
    "Baglung / Baglung / Baglung",
    "Baglung / Baglung Bazar / Baglung Bazar",
    "Bagmati (Sarlahi) / Bagmati (Sarlahi) / Bagmati (Sarlahi)",
    "Bahrabise (Sindhupalchowk) / Barhabise (Sindhupalchowk) / Barhabise (Sindhupalchowk)",
    "Bandipur (Tanahun) / Bandipur (Tanahun) / Bandipur (Tanahun)",
    "Banepa / Banepaa / Banepa",
    "Banepa / Nala / Nala",
    "Bansagadhi (Bardiya) / Bansagadhi (Bardiya) / Bansagadhi (Bardiya)",
    "Barahakshetra (Dharan) / Barahakshetra (Dharan) / Barahakshetra (Dharan)",
    "Barathwa Sarlahi / Barathwa Sarlahi / Barathwa Sarlahi",
    "Bardaghat / Bardaghat / Bardaghat (Nawalparasi)",
    "Bardibas / Bardibas / Bardibas",
    "Bardibas / Gaushala (Bardibas) / Gaushala (Bardibas)",
    "Bardibas / Ishworpur (Bardibas) / Ishworpur (Bardibas)",
    "Basantapur (Terhathum) / Basantapur (Terhathum) / Basantapur (Terhathum)",
    "Battar Bazar (Nuwakot) / Battar Bazar (Nuwakot) / Battar Bazar (Nuwakot)",
    "Belauri (Kanchanpur) / Belauri (Kanchanpur) / Belauri (Kanchanpur)",
    "Belbari (Morang) / Bahuni Bazaar (Morang) / Bahuni Bazaar (Morang)",
    "Belbari (Morang) / Belbari (Morang) / Belbari (Morang)",
    "Beltar (Udayapur) / Basaha / Basaha",
    "Beltar (Udayapur) / Beltar (Udayapur) / Beltar (Udayapur)",
    "Beni Bazar / Beni Bazar / Beni Bazar",
    "Bhadrapur (Jhapa) / Baniyani (Jhapa) / Baniyani (Jhapa)",
    "Bhadrapur (Jhapa) / Bhadrapur Bazaar / Bhadrapur Bazaar",
    "Bhadrapur (Jhapa) / Bhadrapur Bazar / Bhadrapur Bazar",
    "Bhadrapur (Jhapa) / Chandragadhi (Jhapa) / Chandragadhi (Jhapa)",
    "Bhadrapur (Jhapa) / Puhatubari (Jhapa) / Puhatubari (Jhapa)",
    "Bhadrapur (Jhapa) / Saharedangi (Jhapa) / Saharedangi (Jhapa)",
    "Bairahawa / Amuwa / Amuwa (Rupandehi)",
    "Bhairahawa / Bhairahawa / Bhairahawa",
    "Bhakundebesi (Kavre) / Bhakundebesi (Kavre) / Bhakundebesi (Kavre)",
    "Bhaluwang (Dang) / Bhaluwang (Dang) / Bhaluwang (Dang)",
    "Bhaluwang (Dang) / Deukhuri / Deukhuri",
    "Bhaluwang (Dang) / Gadhwa / Gadhwa",
    "Bhaluwang (Dang) / kalakate / kalakate",
    "Bhaluwang (Dang) / Lamahi / Lamahi (Dang)",
    "Bhaluwang (Dang) / Mourighat / Mourighat",
    "Bhaluwang (Dang) / Pipari / Pipari",
    "Bhaluwang (Dang) / Sisahaniya / Sisahaniya",
    "Bhantabari (Sunsari) / Bhantabari (Sunsari) / Bhantabari (Sunsari)",
    "Bharatpur (Chitwan) / 26 No. Ward Office / 26 No. Ward Office",
    "Bharatpur (Chitwan) / 7 No.Chowk / 7 No.Chowk",
    "Bharatpur (Chitwan) / Aaptari / Aaptari",
    "Bharatpur (Chitwan) / Amrit Chowk / Amrit Chowk",
    "Bharatpur (Chitwan) / Andrauli / Andrauli",
    "Bharatpur (Chitwan) / Bankatta / Bankatta",
    "Bharatpur (Chitwan) / Baseni / Baseni",
    "Bharatpur (Chitwan) / Bhaga / Bhaga",
    "Bharatpur (Chitwan) / Bharatpur / Bharatpur",
    "Bharatpur (Chitwan) / Bharatpur (Chitwan) / Bharatpur (Chitwan)",
    "Bharatpur (Chitwan) / Bharatpur (Chitwan) / Dashdhunga",
    "Bharatpur (Chitwan) / Bharatpur (Chitwan) / Devnagar",
    "Bharatpur (Chitwan) / Bhateri / Bhateri",
    "Bharatpur (Chitwan) / Bhojad / Bhojad",
    "Bharatpur (Chitwan) / Buddhanagar / Buddhanagar",
    "Bharatpur (Chitwan) / Champhanagar / Champhanagar",
    "Bharatpur (Chitwan) / Chanauli / Chanauli",
    "Bharatpur (Chitwan) / Dhurba / Dhurba",
    "Bharatpur (Chitwan) / Gaurianj / Gaurianj",
    "Bharatpur (Chitwan) / Geetangar / Geetangar",
    "Bharatpur (Chitwan) / Gitanagar / Gitanagar",
    "Bharatpur (Chitwan) / Golaghat / Golaghat",
    "Bharatpur (Chitwan) / Gondrang / Gondrang",
    "Bharatpur (Chitwan) / Jugedi / Jugedi",
    "Bharatpur (Chitwan) / Jyotinagar / Jyotinagar",
    "Bharatpur (Chitwan) / Khadrauli Chowk / Khadrauli Chowk",
    "Bharatpur (Chitwan) / Khahare Khola Pul / Khahare Khola Pul",
    "Bharatpur (Chitwan) / Krishna Chowk / Krishna Chowk",
    "Bharatpur (Chitwan) / Labernagar / Labernagar",
    "Bharatpur (Chitwan) / Meghauli / Meghauli",
    "Bharatpur (Chitwan) / Muktara Chowk / Muktara Chowk",
    "Bharatpur (Chitwan) / Narayangarh / Narayangarh",
    "Bharatpur (Chitwan) / Naurange / Naurange",
    "Bharatpur (Chitwan) / Padampokhari / Padampokhari",
    "Bharatpur (Chitwan) / Pakaudi / Pakaudi",
    "Bharatpur (Chitwan) / Parsa Dhap / Parsa Dhap",
    "Bharatpur (Chitwan) / Patihani / Patihani",
    "Bharatpur (Chitwan) / Pokhara Bus Park / Pokhara Bus Park",
    "Bharatpur (Chitwan) / Prembasti / Prembasti",
    "Bharatpur (Chitwan) / Ramghat / Ramghat",
    "Bharatpur (Chitwan) / Ramngar / Ramngar",
    "Bharatpur (Chitwan) / Sajhapur / Sajhapur",
    "Bharatpur (Chitwan) / Sharadpur / Sharadpur",
    "Bharatpur (Chitwan) / Shivaghat / Shivaghat",
    "Bharatpur (Chitwan) / Sukranagar / Sukranagar",
    "Bharatpur (Chitwan) / Telauli / Telauli",
    "Bharatpur (Chitwan) / Ujjawalnagar / Ujjawalnagar",
    "Bhimad (Tanahun) / Bhimad (Tanahun) / Bhimad (Tanahun)",
    "Bhiman (Sindhuli) / Bhiman (Sindhuli) / Bhiman (Sindhuli)",
    "Bhingri(Pyuthan) / Bhingri(Pyuthan) / Bhingri(Pyuthan)",
    "Bhojpur Bazar / Bhojpur Bazar / Bhojpur Bazar",
    "Bhojpur Bazar / Bhojpur Bazar / Bhojpur Bazzar",
    "Bhorletar (Lamjung) / Bhorletar (Lamjung) / Bhorletar (Lamjung)",
    "Bhuriguan (Bardiya) / Bhuriguan (Bardiya) / Bhuriguan (Bardiya)",
    "Biratnagar / Bansi Chowk / Bansi Chowk",
    "Biratnagar / Biratnagar / Biratnagar",
    "Biratnagar / Duhabi (Biratnagar) / Duhabi (Biratnagar)",
    "Biratnagar / Hatkhola / Hatkhola (Biratnagar)",
    "Biratnagar / Hatkhola (Biratnagar) / Hatkhola (Biratnagar)",
    "Biratnagar / Rampur (Biratnagar) / Rampur (Biratnagar)",
    "Biratnagar / Rangeli (Biratnagar) / Rangeli (Biratnagar)",
    "Biratchowk (Morang) / Biratchowk (Morang) / Biratchowk (Morang)",
    "Birendranagar (Surkhet) / Birendranagar (Surkhet) / Birendranagar (Surkhet)",
    "Birgunj / Aadarshnagar (Birgunj) / Aadarshnagar (Birgunj)",
    "Birgunj / Birgunj Bazar / Birgunj Bazar",
    "Birtamod / Arjundhara (Birtamod) / Arjundhara (Birtamod)",
    "Birtamod / Beldangi (Jhapa) / Beldangi (Jhapa)",
    "Birtamod / Biratpokhar (Birtamod) / Biratpokhar (Birtamod)",
    "Birtamod / Birtamod / Birtamod",
    "Birtamod / Birtamod Bazaar / Birtamod Bazaar",
    "Birtamod / Budhabare (Jhapa) / Budhabare (Jhapa)",
    "Birtamod / Buttabari (Jhapa) / Buttabari (Jhapa)",
    "Birtamod / Charali (Jhapa) / Charali (Jhapa)",
    "Birtamod / Danabari (Jhapa) / Danabari (Jhapa)",
    "Birtamod / Domukha (Jhapa) / Domukha (Jhapa)",
    "Birtamod / Durgapur (Jhapa) / Chandranigahapur (Rautahat)",
    "Birtamod / Durgapur (Jhapa) / Durgapur (Jhapa)",
    "Birtamod / Duwagadhi (Jhapa) / Duwagadhi (Jhapa)",
    "Birtamod / Garamuni Bazaar (Jhapa) / Garamuni Bazaar (Jhapa)",
    "Birtamod / Ghailadubba (Jhapa) / Ghailadubba (Jhapa)",
    "Birtamod / Goldhaap (Jhapa) / Goldhaap (Jhapa)",
    "Birtamod / Haldibari (Jhapa) / Haldibari (Jhapa)",
    "Birtamod / Jalthal (Jhapa) / Jalthal (Jhapa)",
    "Birtamod / Jamunbari (Jhapa) / Jamunbari (Jhapa)",
    "Birtamod / Jayapur (Jhapa) / Jayapur (Jhapa)",
    "Birtamod / Kalisthan (Jhapa) / Kalisthan (Jhapa)",
    "Birtamod / Kaptaanbari (Jhapa) / Kaptaanbari (Jhapa)",
    "Birtamod / Khudunabari (Jhapa) / Khudunabari (Jhapa)",
    "Birtamod / Laxmipur (Jhapa) / Laxmipur (Jhapa)",
    "Birtamod / Rajgadh (Jhapa) / Rajgadh (Jhapa)",
    "Birtamod / Salbari (Jhapa) / Salbari (Jhapa)",
    "Birtamod / Sanischare (Jhapa) / Sanischare (Jhapa)",
    "Birtamod / Surunga (Jhapa) / Surunga (Jhapa)",
    "Bodebarsain (Saptari) / Bodebarsain (Saptari) / Bodebarsain (Saptari)",
    "Budar (Doti) / Budar (Doti) / Budar (Doti)",
    "Budhabare (Birtamode) / Budhabare (Birtamode) / Budhabare (Birtamode)",
    "Burtibang (Baglung) / Burtibang (Baglung) / Burtibang (Baglung)",
    "Butwal / Belbas / Belbas",
    "Butwal / Buddhanagar - Naharpur / Buddhanagar - Naharpur",
    "Butwal / Buspark Area / Buspark Area",
    "Butwal / Butwal Campus Area / Butwal Campus Area",
    "Butwal / Butwal Industrial Area / Butwal Industrial Area",
    "Butwal / Chauraha / Chauraha",
    "Butwal / Deep Nagar / Deep Nagar",
    "Butwal / Devinagar / Devinagar",
    "Butwal / Golpark / Golpark",
    "Butwal / Haatbazaar Area / Haatbazaar Area",
    "Butwal / Kalika Nagar / Kalika Nagar",
    "Butwal / Kalikanagar (Butwal) / Kalikanagar (Butwal)",
    "Butwal / Laxminagar / Laxminagar",
    "Butwal / Maina Bagar Area / Maina Bagar Area",
    "Butwal / Majuwa / Majuwa",
    "Butwal / Milan Chowk / Milan Chowk",
    "Butwal / Motipur Area / Motipur Area",
    "Butwal / Nayagaun / Nayagaun",
    "Butwal / Ramnagar / Ramnagar",
    "Butwal / Semlar Area / Semlar Area",
    "Butwal / Sukhha Nagar / Sukhha Nagar",
    "Butwal / Tamnagar / Tamnagar",
    "Butwal / Traffic Chowk Area / Traffic Chowk Area",
    "Butwal / Yogi Kuti Area / Yogi Kuti Area",
    "Chainpur (Bajhang) / Bajhang bagthala / bajhang bagthala",
    "Chainpur (Bajhang) / Chainpur (Bajhang) / Chainpur (Bajhang)",
    "Chainpur (Sankhuwasabha) / Chainpur (Sankhuwasabha) / Chainpur (Sankhuwasabha)",
    "Chainpur(Bajhang) / Bajhang Kedarseu / Bajhang Kedarseu",
    "Chainpur(Bajhang) / Chainpur(Bajhang) / Chainpur(Bajhang)",
    "Chandrauta (Kapilvastu) / Chandrauta (Kapilvastu) / Chandrauta (Kapilvastu)",
    "Charaali (Jhapa) / Charaali (Jhapa) / Charaali (Jhapa)",
    "Chatara(Dharan) / Chatara(Dharan) / Chatara(Dharan)",
    "Chaurjahari(Rukum) / Chaurjahari(Rukum) / Chaurjahari(Rukum)",
    "Chautara (Sindhupalchwok) / Chautara (Sindhupalchwok) / Chautara (Sindhupalchwok)",
    "Chhatar sukrabare / Chhatar sukrabare / Chhatar sukrabare",
    "Chitwan / 200 Bigha / 200 Bigha",
    "Chitwan / 200 bigaha / 200 bigaha",
    "Chitwan / APF Barrack / APF Barrack",
    "Chitwan / Ananda Chowk / Ananda Chowk",
    "Chitwan / Aviyan / Aviyan",
    "Chitwan / Bastola Chowk / Bastola Chowk",
    "Chitwan / Beldiya School / Beldiya School",
    "Chitwan / Bhandara / Bhandara",
    "Chitwan / Bhandara (Chitwan) / Bhandara (Chitwan)",
    "Chitwan / Bhateni / Bhateni",
    "Chitwan / Bhimwali Mandir Lauhre Chowk / Bhimwali Mandir Lauhre Chowk",
    "Chitwan / Birendranagar / Birendranagar",
    "Chitwan / Budauli / Budauli",
    "Chitwan / Buddha Shanti School / Buddha Shanti School",
    "Chitwan / Chaukidada / Chaukidada",
    "Chitwan / Chisapani / Chisapani",
    "Chitwan / Chitwan / Badahara",
    "Chitwan / Chitwan / Chitwan",
    "Chitwan / Chitwan / Holy land road",
    "Chitwan / Chitwan / Khairahani chowk",
    "Chitwan / Chitwan / Khanepani chowk",
    "Chitwan / Chitwan / Sainik school",
    "Chitwan / Chitwan (Madi) / Chitwan (Madi)",
    "Chitwan / Club Chowk / Club Chowk",
    "Chitwan / Congrees Chowk / Congrees Chowk",
    "Chitwan / Daduwa / Daduwa",
    "Chitwan / Dhusari / Dhusari",
    "Chitwan / Disney Park / Disney Park",
    "Chitwan / Gadauli / Gadauli",
    "Chitwan / Gadeuli / Gadeuli",
    "Chitwan / Gaduwa / Gaduwa",
    "Chitwan / Gairibari Chowk / Gairibari Chowk",
    "Chitwan / Gumba Chowk / Gumba Chowk",
    "Chitwan / Hardi chowk / Hardi chowk",
    "Chitwan / Harnari / Harnari",
    "Chitwan / Helthpost Chowk / Helthpost Chowk",
    "Chitwan / Highschool / Highschool",
    "Chitwan / Holy Land Road / Holy Land Road",
    "Chitwan / Jhurjhure / Jhurjhure",
    "Chitwan / Jyotinagar (Chitwan) / Jyotinagar (Chitwan)",
    "Chitwan / Kalika Mandir / Kalika Mandir",
    "Chitwan / Khairahani Chowk / Khairahani Chowk",
    "Chitwan / Khanepani Chowk / Khanepani Chowk",
    "Chitwan / Korean School Chowk / Korean School Chowk",
    "Chitwan / Lankaline / Lankaline",
    "Chitwan / Laxmi Narayan / Laxmi Narayan",
    "Chitwan / Lothar / Lothar",
    "Chitwan / Magani School / Magani school",
    "Chitwan / Magani chowk / Magani chowk",
    "Chitwan / Namuna Petrol Pump / Namuna Petrol Pump",
    "Chitwan / Narayanghat (Chitwan) / Narayanghat (Chitwan)",
    "Chitwan / Padampur / Padampur",
    "Chitwan / Pampa pul / Pampa pul",
    "Chitwan / Parsa chowk / Parsa chowk",
    "Chitwan / Phasera / Phasera",
    "Chitwan / Praksh Medical / Praksh Medical",
    "Chitwan / Purano parsa / Purano Parsa",
    "Chitwan / Sainik School / Sainik School",
    "Chitwan / Salauli / Salauli",
    "Chitwan / Sauraha (Chitwan) / Sauraha (Chitwan)",
    "Chitwan / Shanti bazar / Shanti bazar",
    "Chitwan / Shaktikhor / Shaktikhor",
    "Chitwan / Surtani / Surtani",
    "Chitwan / Tiwari Chowk / Tiwari Chowk",
    "Chuhan Danda / Chuhan Danda / Chuhan Danda",
    "Dadeldhura / Amargadi (Dadeldhura) / Amargadi (Dadeldhura)",
    "Dailekh Bazar / Dailekh Bazar / Dailekh Bazar",
    "Dakshinkali / Dakshinkalii / Dakshinkali",
    "Damak / Chulachuli (Jhapa) / Chaulachuli (Jhapa)",
    "Damak / Chulachuli (Jhapa) / Tudikhel Area",
    "Damak / Damak / Damak",
    "Damak / Shivasatashi (Jhapa) / Shivasatashi (Jhapa)",
    "Damak / Shivgunj (Jhapa) / Shivgunj (Jhapa)",
    "Daman / Daman / Daman",
    "Damauli / Damauli / Damauli",
    "Dang / Dang / Dang",
    "Darchula / Khalanga (Darchula) / Khalanga (Darchula)",
    "Dhadhing / Dhading Bazar / Dhading Bazar",
    "Dhadhing / Dhading besi / Dhading besi",
    "Dhadhing / Gajuri (Dhading) / Gajuri (Dhading)",
    "Dhadhing / Malekhu (Dhading) / Malekhu (Dhading)",
    "Dhakadahi (Bhairahwa) / Dhakadahi (Bhairahwa) / Dhakadahi (Bhairahwa)",
    "Dhalkebar (Dhanusa) / Dhalkebar (Dhanusa) / Dhalkebar (Dhanusa)",
    "Dhangadhi / Dhangadhi / Dhangadhi",
    "Dhangadi / Gauriganga (Dhangadi) / Gauriganga (Dhangadi)",
    "Dhankuta / Bhedetar (Dhankuta) / Bhedetar (Dhankuta)",
    "Dhankuta / Dhankuta / Dhankuta",
    "Dhankuta / Dhankuta / Dhankuta Bazar",
    "Dhankuta / Hile (Dhunkuta) / Hile (Dhunkuta)",
    "Dhankuta / Pakhribas (Dhankuta) / Pakhribas (Dhankuta)",
    "Dhankuta / Rajarani(Dhankuta) / Rajarani(Dhankuta)",
    "Dhanusha / Dhanushadham / Dhanushadham",
    "Dhanusha / Nagraain (Dhanusha) / Nagraain (Dhanusha)",
    "Dhanusha / Sabaila (Dhanusha) / Sabaila (Dhanusha)",
    "Dhanusha / Tinkoriya (Dhanusha) / Tinkoriya (Dhanusha)",
    "Dhanusha / Tulsiyahi (Dhanusha) / Tulsiyahi (Dhanusha)",
    "Dharapani (Manang) / Dharapani (Manang) / Dharapani (Manang)",
    "Dharan / Dharan / Dharan",
    "Dharan / Panbari (Dharan) / Panbari (Dharan)",
    "Dhulabari (Jhapa) / Bahundangi (Jhapa) / Bahundangi (Jhapa)",
    "Dhulabari (Jhapa) / Dhaijan (Jhapa) / Dhaijan (Jhapa)",
    "Dhulabari (Jhapa) / Dhulabari (Jhapa) / Dhulabari (Jhapa)",
    "Dhulabari (Jhapa) / Jyamirgadhi (Jhapa) / Jyamirgadhi (Jhapa)",
    "Dhulabari (Jhapa) / Kakarvitta (Jhapa) / Kakarvitta (Jhapa)",
    "Dhulabari (Jhapa) / Mechinagar (Jhapa) / Mechinagar (Jhapa)",
    "Dhulegauda / Dhulegauda / Dhulegauda",
    "Dhulikhel / Dhulikhel / Dhulikhel",
    "Dhunche (Rasuwa) / Dhunche (Rasuwa) / Dhunche (Rasuwa)",
    "Diktel Bazar(Khotang) / Diktel Bazar(Khotang) / Diktel Bazar",
    "Dingla (Bhojpur) / Dingla (Bhojpur) / Dingla (Bhojpur)",
    "Dolakha / Charikot (Dolakha) / Charikot (Dolakha)",
    "Dolakha / Dolakha / Dolakha",
    "Dolakha / Jiri / Jiri (Dolakha)",
    "Dolalghat / Dolalghat / Dolalghat",
    "Doti / Budar (Doti) / Budar (Doti)",
    "Doti / Rajpur Dipayal (Doti) / Rajpur Dipayal (Doti)",
    "Dudhauli (Sindhuli) / Dudhauli / Dudhauli",
    "Dudhe (Jhapa) / Dudhe (Jhapa) / Dudhe (Jhapa)",
    "Duduwa (Banke) / Duduwa (Banke) / Duduwa (Banke)",
    "Duhabi (Biratnagar) / Duhabi (Sunsari) / Duhabi (Sunsari)",
    "Dulari (Itahari) / Dulari (Itahari) / Dulari (Itahari)",
    "Dulegauda (Tanahu) / Dulegauda (Tanahu) / Dulegauda (Tanahu)",
    "Dumkibas (Nawalparasi) / Dumkibas / Dumkibas (Nawalparasi)",
    "Dumre / Dumre / Dumre",
    "Dunai (Dolpa) / Dunai (Dolpa) / Dunai (Dolpa)",
    "Fikkal (Ilam) / Fikkal (Ilam) / Fikkal (Ilam)",
    "Gaighat (Udayapur) / Gaighat (Udayapur) / Gaighat (Udayapur)",
    "Gaindakot (Chitwan) / Bhirkuti Chowk / Bhirkuti Chowk",
    "Gaindakot (Chitwan) / Bijaya Chowk / Bijaya Chowk",
    "Gaindakot (Chitwan) / Bikash Chowk / Bikash Chowk",
    "Gaindakot (Chitwan) / British Camp / British Camp",
    "Gaindakot (Chitwan) / Chandani Chowk / Chandani Chowk",
    "Gaindakot (Chitwan) / Chauki / Chauki",
    "Gaindakot (Chitwan) / Congress Chowk / Congress Chowk",
    "Gaindakot (Chitwan) / Fedi / Fedi",
    "Gaindakot (Chitwan) / Gairi / Gairi",
    "Gaindakot (Chitwan) / Gaindakot (Chitwan) / Gaindakot (Chitwan)",
    "Gaindakot (Chitwan) / Janak School / Janak School",
    "Gaindakot (Chitwan) / Janaki Gas / Janaki Gas",
    "Gaindakot (Chitwan) / Jayashree Pul / Jayashree Pul",
    "Gaindakot (Chitwan) / Kalika Chowk(Chitwan) / Kalika Chowk(Chitwan)",
    "Gaindakot (Chitwan) / Kishan Chowk / Kishan Chowk",
    "Gaindakot (Chitwan) / Lakhan Chowk / Lakhan Chowk",
    "Gaindakot (Chitwan) / Maula Kalika / Maula Kalika",
    "Gaindakot (Chitwan) / Milan Chowk(Chitwan) / Milan Chowk(Chitwan)",
    "Gaindakot (Chitwan) / Namaste Chowk / Namaste Chowk",
    "Gaindakot (Chitwan) / Silanayas Chowk / Silanayas Chowk",
    "Gaindakot (Chitwan) / Thums / Thums",
    "Gairapatan (Pokhara) / Gairapatan (Pokhara) / Gairapatan (Pokhara)",
    "Gajuri (Dhading) / Gajuri (Dhading) / Gajuri (Dhading)",
    "Galkot (Baglung) / Galkot (Baglung) / Galkot (Baglung)",
    "Galyang (Syangja) / Galyang (Syangja) / Galyang (Syangja)",
    "Garuda (Rahutahat) / Garuda (Rahutahat) / Garuda (Rahutahat)",
    "Gaushala (Mahottari) / Gaushala (Mahottari) / Gaushala (Mahottari)",
    "Gaur (Rautahat) / Gaur (Rautahat) / Gaur (Rautahat)",
    "Gauradaha (Jhapa) / Gauradaha (Jhapa) / Gauradaha (Jhapa)",
    "Gauriganj (Jhapa) / Gauriganj (Jhapa) / Gauriganj (Jhapa)",
    "Gavar (Banke) / Gavar (Banke) / Gavar (Banke)",
    "Ghorahi (Dang) / Ghorahi (Dang) / Ghorahi (Dang)",
    "Gokuleshwar (Baitadi) / Gokuleshwar (Baitadi) / Gokuleshwar (Baitadi)",
    "Golbazar (Lahan) / Golbazar (Lahan) / Golbazar (Lahan)",
    "Gorkha Bazar / Chhepetar (Gorkha) / Chhepetar (Gorkha)",
    "Gorkha Bazar / Gorkha Bazar / Gorkha Bazar",
    "Gorkha Bazar / Manakamana (Gorkha) / AanbuKhaireni",
    "Gorkha Bazar / Manakamana (Gorkha) / Manakamana (Gorkha)",
    "Gorkha Bazar / Palungtar (Gorkha) / Palungtar (Gorkha)",
    "Gorusinge (kapilvastu) / Gorusinge (kapilvastu) / Gorusinge (kapilvastu)",
    "Gothalapani (Baitadi) / Gothalapani (Baitadi) / Gothalapani (Baitadi)",
    "Gulariya (Bardiya) / Geruwa (Bardiya) / Geruwa (Bardiya)",
    "Gulariya (Bardiya) / Gulariya (Bardiya) / Gulariya (Bardiya)",
    "Gulmi Tamghas / Baletaxar (Gulmi) / Baletaxar (Gulmi)",
    "Gulmi Tamghas / Gulmi / Gulmi",
    "Gulmi Tamghas / Gulmi Tamghas / Gulmi Tamghas",
    "Gulmi Tamghas / Ridi/Ruru (Gulmi) / Ridi/Ruru (Gulmi)",
    "Gulmi Tamghas / Shantipur (Gulmi) / Shantipur (Gulmi)",
    "Gulmi Tamghas / Wamitakshar (Gulmi) / Wamitakshar (Gulmi)",
    "Hanumannagar (Saptari) / Hanumannagar (Saptari) / Hanumannagar (Saptari)",
    "Haripur Sarlahi / Haripur Sarlahi / Haripur Sarlahi",
    "Hariwan (Sarlahi) / Hariwan (Sarlahi) / Hariwan (Sarlahi)",
    "Hemja (Pokhara) / Hemja (Pokhara) / Hemja (Pokhara)",
    "Hetauda / Bastipur Makwanpur (Hetauda) / Bastipur Makwanpur (Hetauda)",
    "Hetauda / Bhimphedi (Hetauda) / Bhimphedi (Hetauda)",
    "Hetauda / Hetauda / Hetauda",
    "Hetauda / Hetauda / Piple",
    "Hetauda / Manahari (Makwanpur) / Manahari (Makwanpur)",
    "Hile (Dhankuta) / Hile (Dhunkuta) / Hile (Dhunkuta)",
    "Ilam / Ilam / Ilam",
    "Ilam / Pashupatinath (Ilam) / Pashupatinath (Ilam)",
    "Inaruwa (Sunsari) / Inaruwa (Sunsari) / Inaruwa (Sunsari)",
    "Itahari / Dulari (Itahari) / Dulari (Itahari)",
    "Itahari / Gachhiya (Itahari) / Gachhiya (Itahari)",
    "Itahari / Halgada chowk / Halgada chowk",
    "Itahari / Itahari / Itahari",
    "Itahari / Jhumka (Sunsari) / Jhumka (Sunsari)",
    "Itahari / Karsiya Bazaar (Morang) / Karsiya Bazaar (Morang)",
    "Itahari / Ramailo (Morang) / Ramailo (Morang)",
    "Itahari / Salakpur (Itahari) / Salakpur (Itahari)",
    "Itahari / Sonapur (Itahari) / Sonapur (Itahari)",
    "Itahari / Tarahara(Sunsari) / Tarahar (Sunsari)",
    "Itahari / Bhatbhateni (Itahari) / Bhatbhateni (Itahari)",
    "Janakpur / Balawa (Mahottari) / Balawa (Mahottari)",
    "Janakpur / Jaleshwor / Jaleshwor",
    "Janakpur / Janakpur / Janakpur",
    "Janakpur / Loharpatti (Mahottari) / Loharpatti (Mahottari)",
    "Janakpur / Mahendranagar (Janakpur) / Janakpur",
    "Janakpur / Mahendranagar (Janakpur) / Mahendranagar (Janakpur)",
    "Janakpur / Matihani (Mahottari) / Matihani (Mahottari)",
    "Janakpur / Pipra (Janakpur) / Pipra (Janakpur)",
    "Jeetpur (Bara) / Jeetpur (Bara) / Jeetpur (Bara)",
    "Jeetpur No.4 (Kapilvastu) / Jeetpur No.4 (Kapilvastu) / Jeetpur No.4 (Kapilvastu)",
    "Jhiljhile (Damak) / Jhiljhile (Damak) / Jhiljhile (Damak)",
    "Jogikuti (Rupandehi) / Jogikuti (Rupandehi) / Jogikuti (Rupandehi)",
    "Jomsom Bazar (Mustang) / Jomsom Bazar (Mustang) / Jomsom Bazar (Mustang)",
    "Jumla Bazar / Jumla Bazar / Jumla Bazar",
    "Kadmaha (Saptari) / Bhedetar (Dhankuta) / Bhedetar (Dhankuta)",
    "Kadmaha (Saptari) / Kadmaha (Saptari) / Kadmaha (Saptari)",
    "Kalabanjar (Sunsari) / Kalabanjar (Sunsari) / Kalabanjar (Sunsari)",
    "Kalaiya (Bara) / Kalaiya (Bara) / Kalaiya (Bara)",
    "Kalikot / Kalikot / Kalikot",
    "Kalyanpur (Saptari) / Kalyanpur (Saptari) / Kalyanpur (Saptari)",
    "Kanepokhari (Morang) / Kanepokhari (Morang) / Kanepokhari (Morang)",
    "Kapilvastu / Baidauli (Kapilvastu) / Baidauli (Kapilvastu)",
    "Kapilvastu / Ganeshpur (Kapilvastu) / Ganeshpur (Kapilvastu)",
    "Kapilvastu / Jeetpur Char Number (Kapilvastu) / Jeetpur Char Number (Kapilvastu)",
    "Kapilvastu / Kapilvastu / Kapilvastu",
    "Kapilvastu / Labani (Rupandehi) / Labani (Rupandehi)",
    "Kapilvastu / Maharajgunj (Kapilvastu) / Maharajgunj (Kapilvastu)",
    "Kapilvastu / Odari (Kapilvastu) / Odari (Kapilvastu)",
    "Katari / Katari / Katari",
    "Katari / Katari (Udayapur) / Katari (Udayapur)",
    "Kathmandu Valley / Airport Area / Airport Area",
    "Kathmandu Valley / Alok Nagar / Alok Nagar",
    "Kathmandu Valley / Anamnagar / Anamnagar",
    "Kathmandu Valley / Ason / Ason",
    "Kathmandu Valley / Babarmahal / Babarmahal",
    "Kathmandu Valley / Badegaun / Godawari Residential School",
    "Kathmandu Valley / Badikhel / Badikhel Bus Park",
    "Kathmandu Valley / Bafal / Bafal",
    "Kathmandu Valley / Bagbazar / Bagbazar",
    "Kathmandu Valley / Bagdol / Bagdol",
    "Kathmandu Valley / Bakhundol / Plan International Nepal, Country Office",
    "Kathmandu Valley / Bakhundol / Shangrila Blu Hotel",
    "Kathmandu Valley / Bakhundol / Embassy of Norway",
    "Kathmandu Valley / Bakhundol / KORA Creations",
    "Kathmandu Valley / Bakhundol / Koshi Book Store",
    "Kathmandu Valley / Bakhundol / Maxims Banquet",
    "Kathmandu Valley / Balaju / Balaju Park",
    "Kathmandu Valley / Balaju / Manakamana Mandir Kathmandu",
    "Kathmandu Valley / Balaju / Himalayan Yoga Academy",
    "Kathmandu Valley / Balaju / Balaju Bypass",
    "Kathmandu Valley / Balaju / Bohoratar",
    "Kathmandu Valley / Balaju / Bhat-Bhateni Store Balaju",
    "Kathmandu Valley / Balkhu / Yamaha Repair Center",
    "Kathmandu Valley / Balkhu / Bernhardt College",
    "Kathmandu Valley / Balkot / Balkot",
    "Kathmandu Valley / Balkumari / Balkumari",
    "Kathmandu Valley / Baluwatar / Nepal Rastra Bank",
    "Kathmandu Valley / Baluwatar / Prime Minister’s Residence area",
    "Kathmandu Valley / Baluwatar / Tundal Devi Temple",
    "Kathmandu Valley / Baluwatar / IOM International Organization for Migration Nepal",
    "Kathmandu Valley / Banasthali / Transport Management Service Office",
    "Kathmandu Valley / Banasthali / Safety Innovation Pvt. Ltd",
    "Kathmandu Valley / Banasthali / Banasthali Party Palace",
    "Kathmandu Valley / Bangalamukhi / Banglamukhi",
    "Kathmandu Valley / Baneshwor Height / Baneshowr height",
    "Kathmandu Valley / Baniyatar / Baniyatar",
    "Kathmandu Valley / Bansbari / Bansbari",
    "Kathmandu Valley / Basantapur / Basantapur",
    "Kathmandu Valley / Basundhara / Basundhara Chok",
    "Kathmandu Valley / Battishputali / Pashupati vision complex",
    "Kathmandu Valley / Battishputali / Orchid College",
    "Kathmandu Valley / Battishputali / Maiti Nepal",
    "Kathmandu Valley / Battishputali / Velocity Arena- Nepal cricket school",
    "Kathmandu Valley / Battishputali / Brother-mart",
    "Kathmandu Valley / Battishputali / Golden Temple Inn",
    "Kathmandu Valley / Battishputali / Dwarika Hotel",
    "Kathmandu Valley / Bhadrakali / Bhadrakali",
    "Kathmandu Valley / Bhamgal / Bhangal",
    "Kathmandu Valley / Bhangal / Bhangal",
    "Kathmandu Valley / Bhaktapur Durbar Square / Bhaktapur Durbar Square",
    "Kathmandu Valley / Bhaisepati / Eps-Topik UBT building",
    "Kathmandu Valley / Bhaisepati / Wai-Wai Noodles Factory",
    "Kathmandu Valley / Bhaisepati / Dharmikta Church",
    "Kathmandu Valley / Bhaisepati / Mushroom Farm",
    "Kathmandu Valley / Bhaisepati / Bhainsepati Playground",
    "Kathmandu Valley / Bhaisepati / K Mart",
    "Kathmandu Valley / Bhaisepati / Fulbari Marga Bhaisepati",
    "Kathmandu Valley / Bhanimandal Chowk / Alka Hospital 2",
    "Kathmandu Valley / Bhimsengola / Global College International",
    "Kathmandu Valley / Bhimsengola / Chiya Ghar",
    "Kathmandu Valley / Bhimsengola / Kathmandu National School",
    "Kathmandu Valley / Bhimsengola / S.R. GROUP NEPAL PVT. LTD",
    "Kathmandu Valley / BhoteBahal / BhoteBahal",
    "Kathmandu Valley / Bhrikutimandap / Bhrikutimandap",
    "Kathmandu Valley / Bijeshwori / Bijeshwori",
    "Kathmandu Valley / Bijulibazar / Bijulibazar",
    "Kathmandu Valley / Bisankhunarayan / Bishankhu Narayan Temple",
    "Kathmandu Valley / Bishalnagar / Bishalnagar-ktm",
    "Kathmandu Valley / Boudhha / Boudhha Chowk",
    "Kathmandu Valley / Boudhha / Boudhhanath Stupa",
    "Kathmandu Valley / Buddha Nagar / Liverpool International College",
    "Kathmandu Valley / Buddha Nagar / KMC School",
    "Kathmandu Valley / Buddha Nagar / NGO Federation of Nepal (NFN)",
    "Kathmandu Valley / Budhanilkantha / Bhangal (Kalika Park)",
    "Kathmandu Valley / Budhanilkantha / Budhanilkantha Model Community Academy",
    "Kathmandu Valley / Budhanilkantha / Panchakanya Temple",
    "Kathmandu Valley / Budhanilkantha / Chunikhel",
    "Kathmandu Valley / Budhanilkantha / Mahankal",
    "Kathmandu Valley / Budhanilkantha / Pasikot",
    "Kathmandu Valley / Budhanilkantha / Chyasundol",
    "Kathmandu Valley / Budhanilkantha / Budhanilkantha School",
    "Kathmandu Valley / Budhanilkantha / Chapali Bhadrakali",
    "Kathmandu Valley / Budhanilkantha / Golphutar",
    "Kathmandu Valley / Budhanilkantha / Mandikatar",
    "Kathmandu Valley / Bungmati / Bungmati",
    "Kathmandu Valley / Byasi / Byasi",
    "Kathmandu Valley / Chabahil / Guheswori Waste Water Treatment Plant",
    "Kathmandu Valley / Chabahil / KL Tower",
    "Kathmandu Valley / Chabahil / Chabahil Chok",
    "Kathmandu Valley / Chabahil / Medicare Hospital",
    "Kathmandu Valley / Chabahil / Om Hospital & Research Centre Pvt. Ltd.",
    "Kathmandu Valley / Chabahil / Reliance College",
    "Kathmandu Valley / Chagal / Chagal",
    "Kathmandu Valley / Chakrapath / Chakrapath",
    "Kathmandu Valley / Chamati / Valley Cold Store Pvt. Ltd.",
    "Kathmandu Valley / Chandol / Chandol",
    "Kathmandu Valley / Changathali / Changathali",
    "Kathmandu Valley / Changunarayan / Changunarayan",
    "Kathmandu Valley / Chapagaun / Tahakhel",
    "Kathmandu Valley / Chapagaun / Muldole",
    "Kathmandu Valley / Chapagaun / Nayabasti, Serafat",
    "Kathmandu Valley / Chapagaun / Chapagaun Traffic Police Station",
    "Kathmandu Valley / Chapagaun / Bajrabarahi Temple",
    "Kathmandu Valley / Chapagaun / Bajrabarahi Community Hospital",
    "Kathmandu Valley / Chapagaun / Shree Udaya Kharka Secondary School",
    "Kathmandu Valley / Chapagaun Dobato / Chapagaun dobato",
    "Kathmandu Valley / Chappal Karkhana / Chappal Karkhana",
    "Kathmandu Valley / Chardobato / Chardobato",
    "Kathmandu Valley / Chhauni / Mahendra Ratna Campus",
    "Kathmandu Valley / Chhauni / Education Development Unit",
    "Kathmandu Valley / Chhauni / Nepal Telecom Chhauni",
    "Kathmandu Valley / Chhauni / Chhauni Hospital",
    "Kathmandu Valley / Chhauni / ACME Engineering College",
    "Kathmandu Valley / Chhetrapati / Chhetrapati",
    "Kathmandu Valley / Chundevi / Chundevi Temple",
    "Kathmandu Valley / Chundevi / Chundevi Radhe Radhe Gas Suppliers",
    "Kathmandu Valley / Chyamasingh / Chyamasingh",
    "Kathmandu Valley / Chyasal / Chyasal",
    "Kathmandu Valley / Dadhikot / Dadhikot",
    "Kathmandu Valley / Dahachok / Dahachok-ktm",
    "Kathmandu Valley / Dallu / Little Buddha Academy School",
    "Kathmandu Valley / Dallu / Pushpalal Memorial Park",
    "Kathmandu Valley / Dekocha / Dekocha",
    "Kathmandu Valley / Dhalko / Dhalko",
    "Kathmandu Valley / Dhapakhel / Dhapakhel",
    "Kathmandu Valley / Dhapasi / Dhapasi Height",
    "Kathmandu Valley / Dharmasthali / Ganesh Than",
    "Kathmandu Valley / Dharmasthali / Guinness Public Secondary School",
    "Kathmandu Valley / Dharmasthali / Ganesh Mandir",
    "Kathmandu Valley / Dharmasthali / Tarkeshwor Municipality Ward Office Area",
    "Kathmandu Valley / Dharmasthali / North Valley School",
    "Kathmandu Valley / Dharmasthali / Jaranku Pool",
    "Kathmandu Valley / Dharmasthali / Banglamukhi Temple",
    "Kathmandu Valley / Dhobighat / Megha Hospital Pvt. Ltd.",
    "Kathmandu Valley / Dhobighat / Sunrise Towers",
    "Kathmandu Valley / Dhobighat / Our Lady Of Assumption Church",
    "Kathmandu Valley / Dhumbarahi / Gita Gas Udhyog Pvt. Ltd.",
    "Kathmandu Valley / Dhumbarahi / Dhumrabaraha Temple",
    "Kathmandu Valley / Dhumbarahi / The Insight Vision SS/College",
    "Kathmandu Valley / Dhumbarahi / Prolific higher secondary school",
    "Kathmandu Valley / Dhumbarahi / Dhumbarahi Partypalace",
    "Kathmandu Valley / Dhungeadda, Chandragiri / Dhungeadda, Chandragiri",
    "Kathmandu Valley / Dhungedhara (Chhauni) / Dhungedhara",
    "Kathmandu Valley / Dillibazar / Innovation Developers Nepal Private Ltd.",
    "Kathmandu Valley / Dillibazar / Dillibazar Pipalko Bot Bus Stop",
    "Kathmandu Valley / Durbarmarg / Durbarmarg",
    "Kathmandu Valley / Duwakot / Duwakot",
    "Kathmandu Valley / Ekantakuna / Transport Management Office",
    "Kathmandu Valley / Ekantakuna / Embassy of Switzerland",
    "Kathmandu Valley / Gairidhara / Goma Ganesh Petrol Pumb",
    "Kathmandu Valley / Gairigaun / Radhe Radhe Clearing Service",
    "Kathmandu Valley / Gairigaun / Annapurna Vinayak School",
    "Kathmandu Valley / Gathaghar / Gathaghar",
    "Kathmandu Valley / Gaurighat / Gaurighat",
    "Kathmandu Valley / Gausala / Pashupati Electric Crematorium",
    "Kathmandu Valley / Gausala / Nepal Investment Mega Bank ATM",
    "Kathmandu Valley / Gausala / Nepal Ved Vidhyashram Sanskrit Secondary School",
    "Kathmandu Valley / Gausala / Pashupatinath Temple",
    "Kathmandu Valley / Gausala / Nepa Rudraksha",
    "Kathmandu Valley / Gausala / Gausala Chok",
    "Kathmandu Valley / Gausala / Tilganga Hospital Area",
    "Kathmandu Valley / Gausala / Pingalasthan",
    "Kathmandu Valley / Ghattekulo / Suryodaya Sec. School",
    "Kathmandu Valley / Ghattekulo / Akshar Academy",
    "Kathmandu Valley / Ghattekulo / Samiksha Publications (Office)",
    "Kathmandu Valley / Ghattekulo / Sagarmatha Multiple College",
    "Kathmandu Valley / Ghattekulo / Shangrila Tower",
    "Kathmandu Valley / Godawari / Phulchoki Temple",
    "Kathmandu Valley / Godawari / Damaitar Lower Secondary School",
    "Kathmandu Valley / Godawari / Mulpani Youth Club",
    "Kathmandu Valley / Godawari / Godamchaur",
    "Kathmandu Valley / Gokarneshwor / Nayapati",
    "Kathmandu Valley / Gokarneshwor / Baluwa",
    "Kathmandu Valley / Gokarneshwor / Gokarneshwor",
    "Kathmandu Valley / Gongabu / Suryadarshan Height",
    "Kathmandu Valley / Gongabu / Supreme College",
    "Kathmandu Valley / Gongabu / Ganesh Mandir",
    "Kathmandu Valley / Gongabu / Bhat-Bhateni Super Market",
    "Kathmandu Valley / Gothatar / Gothatar",
    "Kathmandu Valley / Grande / Grande International Hospital",
    "Kathmandu Valley / Grande / Greenland High School",
    "Kathmandu Valley / Gurjudhara / Gurjudhara",
    "Kathmandu Valley / Gwarko / Gwarko",
    "Kathmandu Valley / Gyaneshwor / Gyaneshwor",
    "Kathmandu Valley / Hadigaun / Hadigaun",
    "Kathmandu Valley / Harisiddhi / Sofa Point Nepal Pvt. Ltd",
    "Kathmandu Valley / Harisiddhi / Shree Harisiddhi Secondary School",
    "Kathmandu Valley / Harisiddhi / Harisiddhi Futsal",
    "Kathmandu Valley / Harisiddhi / Nepal Plastic Surgery Hospital",
    "Kathmandu Valley / Hattiban / Hattiban",
    "Kathmandu Valley / Hattigauda / Hattigauda",
    "Kathmandu Valley / Hattisar / Hattisar",
    "Kathmandu Valley / Imadol / Rajkulo tol sudhar samiti office",
    "Kathmandu Valley / Imadol / Imadol Swimming Pool",
    "Kathmandu Valley / Imadol / New Bhadrakali Petrol Pump",
    "Kathmandu Valley / Imadol / United School",
    "Kathmandu Valley / Imadol / Central Engineering Campus",
    "Kathmandu Valley / Imadol / KMC Lalitpur",
    "Kathmandu Valley / Indrachok / Indrachok",
    "Kathmandu Valley / Jadibuti / BP Eye Hospital",
    "Kathmandu Valley / Jadibuti / Jadibuti Bus Stop",
    "Kathmandu Valley / Jadibuti / Koteshwor Multiple Campus Area",
    "Kathmandu Valley / Jadibuti / You Tv Nepal",
    "Kathmandu Valley / Jadibuti / Hamro Sahayatri Hospital And Birthing Centre",
    "Kathmandu Valley / Jadibuti / Puspanjali Cinema Hall",
    "Kathmandu Valley / Jadibuti / Jadibuti Bus And Micro Stand",
    "Kathmandu Valley / Jagati / Jagati Bus Stand",
    "Kathmandu Valley / Jagati / Jagati Police Station Area",
    "Kathmandu Valley / Jagati / Doleshwor Chok",
    "Kathmandu Valley / Jamal / Jamal",
    "Kathmandu Valley / Jarankhu / Jarankhu",
    "Kathmandu Valley / Jawalakhel / Central Zoo",
    "Kathmandu Valley / Jawalakhel / Alka Hospital",
    "Kathmandu Valley / Jawalakhel / Nepal Telecom Office",
    "Kathmandu Valley / Jawalakhel / Prasadi Academy",
    "Kathmandu Valley / Jhamsikhel / Star Hospital",
    "Kathmandu Valley / Jhamsikhel / Field Futsal",
    "Kathmandu Valley / Jhaukhel / Jhaukhel",
    "Kathmandu Valley / Jorpati / Jorpati Chok",
    "Kathmandu Valley / Jorpati / Makalbari",
    "Kathmandu Valley / Jorpati / Nepal Medical College Teaching Hospital",
    "Kathmandu Valley / Kadaghari / Kadaghari",
    "Kathmandu Valley / Kageshwari Manohara / Kageshwari Manohara",
    "Kathmandu Valley / Kal Dhara / Kal Dhara",
    "Kathmandu Valley / Kalanki / Malpot Office",
    "Kathmandu Valley / Kalanki / Everest Bank, ATM",
    "Kathmandu Valley / Kalanki / Kalanki City Market",
    "Kathmandu Valley / Kalanki / Kalanki Mandir Bus Stop",
    "Kathmandu Valley / Kalanki / Nepal National Hospital",
    "Kathmandu Valley / Kalanki / Cambridge Intl College",
    "Kathmandu Valley / Kalanki / Sahid Memorial Hospital",
    "Kathmandu Valley / Kalimati / Tahachal Bagaicha",
    "Kathmandu Valley / Kalimati / The Soaltee Kathmandu",
    "Kathmandu Valley / Kalimati / Hyatt Place Kathmandu",
    "Kathmandu Valley / Kalimati / Gyanodaya Secondary School",
    "Kathmandu Valley / KamalBinayak / KamalBinayak",
    "Kathmandu Valley / Kamaladi / Kamaladi",
    "Kathmandu Valley / Kamalpokhari / kamalpokhari",
    "Kathmandu Valley / Kapan / Kapan Police Station",
    "Kathmandu Valley / Kapan / Tenzing Chowk",
    "Kathmandu Valley / Kapan / Sarswati Nagar",
    "Kathmandu Valley / Kapan / Football Ground",
    "Kathmandu Valley / Kapurdhara / Kapurdhara",
    "Kathmandu Valley / Karya Binayak / Karya Binayak",
    "Kathmandu Valley / Katunje / Katunje",
    "Kathmandu Valley / Kaushaltar / Kaushaltar",
    "Kathmandu Valley / Kavresthali / Kavresthali",
    "Kathmandu Valley / Kharibot(kapan) / Kharibot(kapan)",
    "Kathmandu Valley / Khokana / Khokana",
    "Kathmandu Valley / Khumaltar / ICIMOD (International Centre for Integrated Mountain Development)",
    "Kathmandu Valley / Khumaltar / Gene Bank",
    "Kathmandu Valley / Khumaltar / Downtown Apartment",
    "Kathmandu Valley / Khumaltar / Ullens School",
    "Kathmandu Valley / Khumaltar / National Agronomy Research Center",
    "Kathmandu Valley / Khumaltar / National Biotechnology Research Centre",
    "Kathmandu Valley / Khusibu / Khusibu",
    "Kathmandu Valley / Kimdol / Kimdol Taxi Park",
    "Kathmandu Valley / Kimdol / BODHISATTVA SCHOOL",
    "Kathmandu Valley / Kimdol / Tevel Nepal",
    "Kathmandu Valley / Koteshwor / Koteshwor",
    "Kathmandu Valley / Koteshwor / Narephate",
    "Kathmandu Valley / Koteshwor / Mahadevasthan Temple",
    "Kathmandu Valley / Koteshwor / Himalaya College",
    "Kathmandu Valley / Koteshwor / Grammar School/College",
    "Kathmandu Valley / Koteshwor / Koteshwor Chowk",
    "Kathmandu Valley / Koteshwor / Munibhairab",
    "Kathmandu Valley / Koteshwor / Sei Engineering College",
    "Kathmandu Valley / Koteshwor / V-s Niketan School",
    "Kathmandu Valley / Koteshwor / Cck (City Center Kathmandu)",
    "Kathmandu Valley / Koteshwor / Jadibuti Chowk",
    "Kathmandu Valley / Koteshwor / Subidhanagar",
    "Kathmandu Valley / Koteshwor / Koteshwor Police Station",
    "Kathmandu Valley / Kuleshwor / Kuleshwor",
    "Kathmandu Valley / Kumarigal / Kumarigal",
    "Kathmandu Valley / Kumaripati / Kumaripati",
    "Kathmandu Valley / Kupandole / Kupandole",
    "Kathmandu Valley / Kusunti / Kusunti",
    "Kathmandu Valley / Lagan / Lagan",
    "Kathmandu Valley / Lagankhel / Lagankhel",
    "Kathmandu Valley / Lainchour / Lainchour",
    "Kathmandu Valley / Lajimpat / Lajimpat",
    "Kathmandu Valley / Lazimpat / Lazimpat",
    "Kathmandu Valley / Lubhu / Lubhu",
    "Kathmandu Valley / Machhapokhari / Machhapokhari",
    "Kathmandu Valley / Madhyapur Thimi / Madhyapur Thimi",
    "Kathmandu Valley / Mahabouddha / Mahabouddha",
    "Kathmandu Valley / Maharajgunj / Maharajgunj",
    "Kathmandu Valley / Maitidevi / Maitidevi",
    "Kathmandu Valley / Maitighar / Maitighar",
    "Kathmandu Valley / Makalbari / Makalbari",
    "Kathmandu Valley / Maligaun / Maligaun",
    "Kathmandu Valley / Mandikatar / Mandikatar",
    "Kathmandu Valley / Mangalbazar / Mangalbazar",
    "Kathmandu Valley / Manmai / Manmai",
    "Kathmandu Valley / Maru / Maru",
    "Kathmandu Valley / Matatirtha / Matatirtha",
    "Kathmandu Valley / Minbhawan / Minbhawan",
    "Kathmandu Valley / Mulpani / Mulpani",
    "Kathmandu Valley / Nardevi / Nardevi",
    "Kathmandu Valley / Naxal / Narayanchaur Park Naxal",
    "Kathmandu Valley / Naxal / Nepal Police Headquarters",
    "Kathmandu Valley / Naxal / Siddhartha Capital Limited",
    "Kathmandu Valley / Nayabazar / Nayabazar",
    "Kathmandu Valley / Nepalgunj / Koreanpur",
    "Kathmandu Valley / Nepaltar / Nepaltar",
    "Kathmandu Valley / New Baneshwar / Civil Service Hospital of Nepal",
    "Kathmandu Valley / New Baneshwar / Beyond Smile Dental Clinic",
    "Kathmandu Valley / New Baneshwar / Eyeplex Mall",
    "Kathmandu Valley / New Baneshwar / Pani Tyanki",
    "Kathmandu Valley / New Baneshwar / Aloknagar",
    "Kathmandu Valley / New Road / Bishalbazar",
    "Kathmandu Valley / New Road / Tamrakar House",
    "Kathmandu Valley / New Road / C.H. Impex",
    "Kathmandu Valley / New Road / Buddha Temple",
    "Kathmandu Valley / Old Baneshwar / Apex College",
    "Kathmandu Valley / Paknajol / Pankajol",
    "Kathmandu Valley / Panipokhari / Nepal Police Hospital",
    "Kathmandu Valley / Panipokhari / T.U. Teaching Hospital",
    "Kathmandu Valley / Panipokhari / U.S. Embassy",
    "Kathmandu Valley / Pashupatinath / Pashupatinth",
    "Kathmandu Valley / Patan / Mangal Bazar",
    "Kathmandu Valley / Patan / Patan Dhoka",
    "Kathmandu Valley / Patan / Banglamukhi",
    "Kathmandu Valley / Patan / Patan Durbarsqure",
    "Kathmandu Valley / Patan / Pimbahal",
    "Kathmandu Valley / Patan / Chhyaybahal",
    "Kathmandu Valley / Patan / Chakupat",
    "Kathmandu Valley / Pepsicola / Pepsicola",
    "Kathmandu Valley / Phutung / Phutung",
    "Kathmandu Valley / Pulchowk / Labim Mall",
    "Kathmandu Valley / Pulchowk / Sajha Yatayat",
    "Kathmandu Valley / Pulchowk / Pulchowk Campus",
    "Kathmandu Valley / Purano Naikap / Purano Naikap",
    "Kathmandu Valley / Putalisadak / Putalisadak",
    "Kathmandu Valley / Radhe Radhe / Radhe Radhe Bus Station",
    "Kathmandu Valley / Radhe Radhe / Bhatbhatni Super Market",
    "Kathmandu Valley / Ramhiti / Ramhiti",
    "Kathmandu Valley / Ravibhawan / Ravibhawan",
    "Kathmandu Valley / Sainbu / Sainbu",
    "Kathmandu Valley / Sallaghari / Chundevi bhaktpur",
    "Kathmandu Valley / Sallaghari / Tuinkune Sallaghari Area",
    "Kathmandu Valley / Sallaghari / Nepal Sbi Bank Ltd",
    "Kathmandu Valley / Sallaghari / Jay Shree Indreni Oxygen Gas Suppliers",
    "Kathmandu Valley / Sallaghari / Lotus International School",
    "Kathmandu Valley / Sallaghari / Srijananagar Overhead Bridge",
    "Kathmandu Valley / Sallaghari / Sallaghari Ground Area",
    "Kathmandu Valley / Sallaghari / Department Of Transport Management, Srijananagar",
    "Kathmandu Valley / Samakhusi / Dakshinkali Mandir",
    "Kathmandu Valley / Samakhusi / Big Mart",
    "Kathmandu Valley / Samakhusi / Samakhusi Chok",
    "Kathmandu Valley / Samakhusi / Nabodit College",
    "Kathmandu Valley / Sanepa / The British School",
    "Kathmandu Valley / Sanepa / Arun Thapa Statue",
    "Kathmandu Valley / Sankhu / Sankhu Police Station",
    "Kathmandu Valley / Sankhu / Sankhu Bus Park",
    "Kathmandu Valley / Sano Bharyang / Sano Bharyang Bus Stop",
    "Kathmandu Valley / Sano Thimi / Sanothimi Campus",
    "Kathmandu Valley / Sano Thimi / Noc (Letter Office)",
    "Kathmandu Valley / Sano Thimi / Sos Children'S Villages",
    "Kathmandu Valley / Sano Thimi / Dhunche Pakha",
    "Kathmandu Valley / Sano Thimi / National Examinations Board",
    "Kathmandu Valley / Sanogau / Sanogau",
    "Kathmandu Valley / Satdobato / Little Angels School",
    "Kathmandu Valley / Satdobato / Radio Nepal Transmission Station",
    "Kathmandu Valley / Satdobato / SalesBerry Department Store",
    "Kathmandu Valley / Satdobato / Satdobato Chok",
    "Kathmandu Valley / Satdobato / Nayabasti",
    "Kathmandu Valley / Satungal / Satungal",
    "Kathmandu Valley / Sesmati / Sesmati",
    "Kathmandu Valley / Shankhamul / Shandar Mo:Mo",
    "Kathmandu Valley / Shankhamul / Shankhamul Futsal",
    "Kathmandu Valley / Shankhamul / Shankhamul Bridge",
    "Kathmandu Valley / Shantinagar / Shantinagar",
    "Kathmandu Valley / Siddhapokhari / Siddhapokhari",
    "Kathmandu Valley / Sinamangal / Kathmandu Medical College",
    "Kathmandu Valley / Sinamangal / Aviation Museum",
    "Kathmandu Valley / Sinamangal / Buddha Air Cargo Sales Office",
    "Kathmandu Valley / Sinamangal / Purbanchal University Office Of Exam Management",
    "Kathmandu Valley / Sinamangal / Sinamangal Chok",
    "Kathmandu Valley / Singha Durbar / Singha Durbar",
    "Kathmandu Valley / Single tree / Single tree",
    "Kathmandu Valley / Siphal / Siphal",
    "Kathmandu Valley / Sirutar / Sirutar",
    "Kathmandu Valley / Sitapaila / New Binay Driving Training Institute.",
    "Kathmandu Valley / Sitapaila / Valley College of Techical Science",
    "Kathmandu Valley / Sitapaila / SalesBerry Department Store",
    "Kathmandu Valley / Sitapaila / Manmohan Memorial Medical College and Teaching Hospital",
    "Kathmandu Valley / Sitapaila / APF barrage",
    "Kathmandu Valley / Sitapaila / Nagarjun Rock Garden",
    "Kathmandu Valley / Sitapaila / Aadeswor Mahadev",
    "Kathmandu Valley / Soltimode / Soltimode",
    "Kathmandu Valley / Sorakhutte / Namaste Cargo",
    "Kathmandu Valley / Sorakhutte / Himalayas Mountain",
    "Kathmandu Valley / Srijana Nagar / Srijana Nagar",
    "Kathmandu Valley / Subidhanagar / Himalayan White House Intl College",
    "Kathmandu Valley / Subidhanagar / College of IT & Engineering",
    "Kathmandu Valley / Subidhanagar / Prabhu Bank Limited",
    "Kathmandu Valley / Sukedhara / Sukedhara Bus Stop",
    "Kathmandu Valley / Sukedhara / Sukedhara Police Beat",
    "Kathmandu Valley / Sukuldhoka / Sukuldhoka",
    "Kathmandu Valley / Sunakothi / Sunakothi",
    "Kathmandu Valley / Sundarijal / Sundarijal",
    "Kathmandu Valley / Sundhara / Sundhara",
    "Kathmandu Valley / Suryabinayak / Kakrabari",
    "Kathmandu Valley / Suryabinayak / Palanse",
    "Kathmandu Valley / Suryabinayak / Nalinchok",
    "Kathmandu Valley / Suryabinayak / Ocimum Nursery",
    "Kathmandu Valley / Suryabinayak / Nangkhel",
    "Kathmandu Valley / Suryabinayak / Nandikeshwar Mahadev Temple",
    "Kathmandu Valley / Suryabinayak / Taudol",
    "Kathmandu Valley / Suryabinayak / Maligaun",
    "Kathmandu Valley / Suryabinayak / Soche",
    "Kathmandu Valley / Suryabinayak / Doleshwornath Mahadev Temple",
    "Kathmandu Valley / Suryabinayak / Sipadol",
    "Kathmandu Valley / Suryabinayak / Katunje",
    "Kathmandu Valley / Suryabinayak / Katunje Police Station",
    "Kathmandu Valley / Suryabinayak / Sushila Bhairab Temple",
    "Kathmandu Valley / Suryabinayak / Latarambeshwor Mahadev",
    "Kathmandu Valley / Suryabinayak / Bindabasini Mandir",
    "Kathmandu Valley / Suryabinayak / Chittapol",
    "Kathmandu Valley / Suryamadi, Bhaktapur / Suryamadi, Bhaktapur",
    "Kathmandu Valley / Swayambhu / Bhagwan Pau",
    "Kathmandu Valley / Swayambhu / Chamati",
    "Kathmandu Valley / Swayambhu / A.V.M Secondary school",
    "Kathmandu Valley / Swayambhu / Banasthali",
    "Kathmandu Valley / Syuchatar / Syuchatar",
    "Kathmandu Valley / Tahachal / Tahachal",
    "Kathmandu Valley / Tahakhel / Tahakhel",
    "Kathmandu Valley / Talchikhel / Talchikhel",
    "Kathmandu Valley / Tangal / Tangal",
    "Kathmandu Valley / Tarkeshwor / Nepaltar",
    "Kathmandu Valley / Teku / Teku Dovan",
    "Kathmandu Valley / Teku / Sukraraj Tropical & Infectious Disease Hospital",
    "Kathmandu Valley / Teku / Shree Pachali Bhairav (Tepa Aaju Dya) Temple",
    "Kathmandu Valley / Teku / Labour And Employment Office, Kathmandu",
    "Kathmandu Valley / Teku / One Ink Tattoo Nepal",
    "Kathmandu Valley / Teku / Teku Police Station",
    "Kathmandu Valley / Thaiba / Thaiba Chok",
    "Kathmandu Valley / Thaiba / Dhusal Dhara",
    "Kathmandu Valley / Thaler / Thaler",
    "Kathmandu Valley / Thali / Thali",
    "Kathmandu Valley / Thamel / Garden of Dreams",
    "Kathmandu Valley / Thamel / Chhaya Center",
    "Kathmandu Valley / Thamel / Astrek Climbing Wall",
    "Kathmandu Valley / Thamel / The Malla Hotel",
    "Kathmandu Valley / Thankot / Taukhel",
    "Kathmandu Valley / Thankot / Thankot",
    "Kathmandu Valley / Thankot / Thankot Bus Park",
    "Kathmandu Valley / Thankot / Satungal",
    "Kathmandu Valley / Thankot / Gurjudhara",
    "Kathmandu Valley / Thankot / Dahachok",
    "Kathmandu Valley / Thankot / Kalupande Danda",
    "Kathmandu Valley / Thankot / Dawadi Gaun",
    "Kathmandu Valley / Thankot / Balambu",
    "Kathmandu Valley / Thapagaun / Thapagaun",
    "Kathmandu Valley / Thapathali / Rosebud School",
    "Kathmandu Valley / Thapathali / Norvic International Hospital",
    "Kathmandu Valley / Thapathali / Oliz Store",
    "Kathmandu Valley / Thapathali / St. Xavier's College",
    "Kathmandu Valley / Thapathali / Nepal Art Council",
    "Kathmandu Valley / Thasikhel / Thasikhel",
    "Kathmandu Valley / Thecho / Thecho",
    "Kathmandu Valley / Thulo Bharyang / Thulo Bharyang Bus Stop",
    "Kathmandu Valley / Tikathali / Tikathali",
    "Kathmandu Valley / Tinkune / Tinkune Chok",
    "Kathmandu Valley / Tokha / Tokha",
    "Kathmandu Valley / Tribhuvan University / Tribhuvan University",
    "Kathmandu Valley / Tripureshwor / Department of Passport",
    "Kathmandu Valley / Tripureshwor / Dasharath Stadium",
    "Kathmandu Valley / Tripureshwor / The British College, Kathmandu",
    "Kathmandu Valley / Uttar Dhoka / Uttar Dhoka",
    "Kathmandu Valley / bode / bode",
    "Kathmandu Valley / sipadol / sipadol",
    "Kawasoti / Amarapuri / Amarapuri",
    "Kawasoti / Bhedabari / Bhedabari",
    "Kawasoti / Devachuli (Kawasoti) / Devachuli (Kawasoti)",
    "Kawasoti / Harkapur / Harkapur",
    "Kawasoti / Kawasoti / Kawasoti",
    "Kawasoti / Malpur / Malpur",
    "Kawasoti / Mukundapur / Mukundapur",
    "Kawasoti / Pitauji / Pitauji",
    "Kerabari (Morang) / Kerabari / Kerabari (Morang)",
    "Kerkha (Damak) / Kerkha (Damak) / Kerkha (Damak)",
    "Khaireni (Rupendehi) / Khaireni (Rupandehi) / Khaireni (Rupandehi)",
    "Khajura (Nepalgunj) / Khajura (Nepalgunj) / Khajura (Nepalgunj)",
    "Khalanga (Jajarkot) / Khalanga (Jajarkot) / Khalanga (Jajarkot)",
    "Khalanga (Salyan) / Khalanga (Salyan) / Khalanga (Salyan)",
    "Khanar (Sunsari) / Khanar (Sunsari) / Khanar (Sunsari)",
    "Khandbari (Sankhuwasabha) / Khandbari (Sankhuwasabha) / Khandbari (Sankhuwasabha)",
    "Khurkot (Sindhuli) / Khurkot (Sindhuli) / Khurkot (Sindhuli)",
    "Kohalpur (Banke) / Kohalpur (Banke) / Kohalpur (Banke)",
    "Kolhabi (Bara) / Kolhabi (Bara) / Kolhabi (Bara)",
    "Kotihawa / Kotihawa / Kotihawa",
    "Kotihawa (Bhairahawa) / Kotihawa (Bhairahawa) / Kotihawa (Bhairahawa)",
    "Krishnanagar (Kapilvastu) / Krishnanagar (Kapilbastu) / Krishnanagar (Kapilbastu)",
    "Kurintar / Kurintar / Kurintar",
    "Kushma (Parbat) / Kushma (Parbat) / Kushma (Parbat)",
    "Lahan / Bariyarpatti (Siraha) / Bariyarpatti (Siraha)",
    "Lahan / Bastipur (Siraha) / Bastipur (Siraha)",
    "Lahan / Dhangadhimai (Siraha) / Dhangadhimai (Siraha)",
    "Lahan / Lahan / Lahan",
    "Lahan / Sukhipur (Lahan) / Sukhipur (Lahan)",
    "Lakeside (Pokhara) / Bagar (Pokhara) / Bagar (Pokhara)",
    "Lakeside (Pokhara) / Bagmara (Pokhara) / Bagmara (Pokhara)",
    "Lakeside (Pokhara) / Chhorepatan / Chhorepatan",
    "Lakeside (Pokhara) / Lakeside (Pokhara) / Lakeside (Pokhara)",
    "Lakeside (Pokhara) / Newroad (Pokhara) / Newroad (Pokhara)",
    "Lakeside (Pokhara) / Srijana Chowk / Srijana Chowk",
    "Lalbandi (Sarlahi) / Bayalbas (Lalbandi) / Bayalbas (Lalbandi)",
    "Lalbandi (Sarlahi) / Lalbandi (Sarlahi) / Lalbandi (Sarlahi)",
    "Lalgadh (Bardibas) / Lalgadh (Bardibas) / Lalgadh (Bardibas)",
    "Lamjung / Besisahar (Lamjung) / Besisahar (Lamjung)",
    "Lamjung / Lamjung / Lamjung",
    "Lamjung / Sundarbazar (Lamjung) / Sundarbazar (Besisahar)",
    "Lamjung (Sundar Bazar) / Sundarbazar / Sundarbazar",
    "Lamki (Kailali) / Lamki (Kailali) / Lamki (Kailali)",
    "Lekhnath (Kaski) / Lekhnath (Kaski) / Lekhnath (Kaski)",
    "Letang (Morang) / Letang (Morang) / Letang (Morang)",
    "Lete (Myagdi) / Lete (Myagdi) / Lete (Myagdi)",
    "Liwang (Rolpa) / Liwang (Rolpa) / Liwang (Rolpa)",
    "Lukla / Lukla / Lukla",
    "Madhumalla (Morang) / Madhumalla (Morang) / Madhumallaa",
    "Mahendranagar (Kanchanpur) / Mahendranagar / Mahendranagar",
    "Mahendranagar (Kanchanpur) / Mahendranagar (Kanchanpur) / Mahendranagar (Kanchanpur)",
    "Mahuli (Saptari) / Mahuli (Saptari) / Mahuli (Saptari)",
    "Mahuli (Saptari) / Sanfebazar(Achham) / Sanfebazar(Achham)",
    "Malangwa (Sarlahi) / Malangwa (Sarlahi) / Malangwa (Sarlahi)",
    "Malekhu (Dhading) / Malekhu (Dhading) / Malekhu (Dhading)",
    "Managiri (Makwanpur) / Manahari (Makwanpur) / Manahari (Makwanpur)",
    "Manakamana (Gorkha) / AanbuKhaireni / Aanbukhaireni",
    "Manang / Manang / Manang",
    "Mangalbare (Morang) / Mangalbare / Mangalbare",
    "Mangalsen (Achham) / Mangalsen (Achham) / Mangalsen (Achham)",
    "Manigram (Rupandehi) / Manigram (Rupandehi) / Manigram (Rupandehi)",
    "Manthali (Ramechhap) / Manthali (Ramechhap) / Manthali (Ramechhap)",
    "Martadi (Bajura) / Martadi (Bajura) / Martadi (Bajura)",
    "Meghauli (Chitwan) / Meghauli (Chitwan) / Meghauli (Chitwan)",
    "Mehelkuna (Surkhet) / Mehelkuna (Surkhet) / Mehelkuna (Surkhet)",
    "Melamchi (Sindhupalchwok) / Melamchi (Sindhupalchwok) / Melamchi (Sindhupalchwok)",
    "Mirchaiya (Siraha) / Mirchaiya (Siraha) / Mirchaiya (Siraha)",
    "Motipur (Rupandehi) / Motipur (Rupandehi) / Motipur (Rupandehi)",
    "Mugu / Mugu / Mugu",
    "Mugling / Mugling / Mugling",
    "Murgiya (Rupandehi) / Murgiya (Rupandehi) / Murgiya (Rupandehi)",
    "Musikot / Musikot Bazar / Musikot",
    "Musikot / Rukum Khalanga Bazar / Khalanga (Rukum)",
    "Myanglung (Terhathum) / Myanglung (Terhathum) / Myanglung (Terhathum)",
    "NAUDANDA KASKI / NAUDANDA KASKI / NAUDANDA KASKI",
    "Nagarkot / Nagarkot / Nagarkot",
    "Nagarkot / Palanse / Palanse",
    "Namche Bazar / Namche Bazar / Namche Bazar",
    "Namobuddha / Namobuddha / Namobuddha",
    "Narainapur (Banke) / Narainapur (Banke) / Narainapur (Banke)",
    "Naubise / Dharke / Dharke",
    "Naubise / Naubise / Naubise",
    "Nepalgunj / Manikapur (Nepalgunj) / Manikapur (Nepalgunj)",
    "Nepalgunj / Nepalgunj / Koreanpur",
    "Nepalgunj / Nepalgunj / Nepalgunj",
    "Nijgadh (Bara) / Nijgadh (Bara) / Nijgadh (Bara)",
    "Nuwakot / Betrawoti Bazar (Nuwakot) / Betrawoti Bazar (Nuwakot)",
    "Nuwakot / Charghare (Nuwakot) / Charghare (Nuwakot)",
    "Nuwakot / Devighat (Nuwakot) / Devighat (Nuwakot)",
    "Nuwakot / Dhunge (Nuwakot) / Dhunge (Nuwakot)",
    "Nuwakot / Durabar Area (Nuwakot) / Durabar Area (Nuwakot)",
    "Nuwakot / Gerkhutar (Nuwakot) / Gerkhutar (Nuwakot)",
    "Nuwakot / Jugetar (Nuwakot) / Jugetar (Nuwakot)",
    "Nuwakot / Kalyanpur (Nuwakot) / Kalyanpur (Nuwakot)",
    "Nuwakot / Khanigaun (Nuwakot) / Khanigaun (Nuwakot)",
    "Nuwakot / Kolani (Nuwakot) / Kolani (Nuwakot)",
    "Nuwakot / Nuwakot Bazar / Battar",
    "Nuwakot / Nuwakot Bazar / Betrawoti Bazar",
    "Nuwakot / Nuwakot Bazar / Bidur",
    "Nuwakot / Nuwakot Bazar / Charghare",
    "Nuwakot / Nuwakot Bazar / Devighat",
    "Nuwakot / Nuwakot Bazar / Dhunge",
    "Nuwakot / Nuwakot Bazar / Durabar Area",
    "Nuwakot / Nuwakot Bazar / Gerkhutar",
    "Nuwakot / Nuwakot Bazar / Jugetar",
    "Nuwakot / Nuwakot Bazar / Kalyanpur",
    "Nuwakot / Nuwakot Bazar / Khanigaun",
    "Nuwakot / Nuwakot Bazar / Kolani",
    "Nuwakot / Nuwakot Bazar / Nuwakot Bazar",
    "Nuwakot / Nuwakot Bazar / Suryagadhi",
    "Nuwakot / Nuwakot Bazar / Trishuli",
    "Nuwakot / Suryagadhi (Nuwakot) / Suryagadhi (Nuwakot)",
    "Nuwakot / Trishuli (Nuwakot) / Trishuli (Nuwakot)",
    "Okhaldhunga Bazar / Okhaldhunga Bazar / Okhaldhunga Bazar",
    "Padsari (Bhairahawa) / Padsari (Bhairahawa) / Padsari (Bhairahawa)",
    "Pakhribas (Dhankuta) / Pakhribas (Dhankuta) / Pakhribas (Dhankuta)",
    "Palpa / Palpa / Palpa",
    "Palung / Palung / Palung",
    "Panauti / Panauti / Panauti",
    "Panchkhal (Kavre) / Panchkhal / Panchkhal",
    "Panchthar / Panchthar / Panchthar",
    "Parsa / Parsa / Parsa",
    "Pashupatinagar (Ilam) / Pashupatinagar (Ilam) / Pashupatinagar (Ilam)",
    "Patan (Baitadi) / Patan (Baitadi) / Patan (Baitadi)",
    "Pathari (Morang) / Pathari (Morang) / Pathari (Morang)",
    "Pathlaiya (Bara) / Pathlaiya (Bara) / Pathlaiya (Bara)",
    "Pharping / Pharping / Pharping",
    "Pharsatikar (Rupandehi) / Pharsatikar (Rupandehi) / Pharsatikar (Rupandehi)",
    "Phattepur (Saptari) / Phattepur (Saptari) / Phattepur (Saptari)",
    "Phidim (Panchthar) / Phidim (Panchthar) / Phidim (Panchthar)",
    "Phungling (Taplejung) / Phungling (Taplejung) / Phungling (Taplejung)",
    "Piprahawa (Banke) / Piprahawa (Banke) / Piprahawa (Banke)",
    "Pokhara / Adarshachwok / Adarsha Chwok",
    "Pokhara / Amarsingh (Pokhara) / Amarsingh (Pokhara)",
    "Pokhara / Archalbot / Archalbot",
    "Pokhara / Argauchowk / Argau chowk",
    "Pokhara / Bagar / Bagar",
    "Pokhara / Bagmara Mathillo Patnyeri / Bagmara Mathillo Patnyeri",
    "Pokhara / Bagmara Pulchok / Bagmara Pulchok",
    "Pokhara / Baskot / Baskot",
    "Pokhara / Begnas Tal / Begnas Tal",
    "Pokhara / Bhagabati Chautara / Bhagabati Chautara",
    "Pokhara / Bhandardhik / Bhandardhik",
    "Pokhara / Bijayapur / Bijayapur",
    "Pokhara / Bindabasini / Bindabasini",
    "Pokhara / Birauta / Birauta",
    "Pokhara / Birauta (Pokhara) / Birauta (Pokhara)",
    "Pokhara / Bote Chautara / Bote Chautara",
    "Pokhara / Budibazar / Budibazar",
    "Pokhara / Chakley Kula / Chakley Kula",
    "Pokhara / Chankhapur / Chankhapur",
    "Pokhara / Chauthe / Chauthe",
    "Pokhara / Chauthe (Pokhara) / Chauthe (Pokhara)",
    "Pokhara / Chinedada / Chinedada",
    "Pokhara / Chipledhunga / Chipledhunga",
    "Pokhara / Chorepatan / Chorepatan",
    "Pokhara / Dadakonak / Dadakonak",
    "Pokhara / Damside / Damside",
    "Pokhara / Deep / Deep",
    "Pokhara / Dhungepatan / Dhungepatan",
    "Pokhara / Digopatan / Digopatan",
    "Pokhara / Gagangaunda / Gagangaunda",
    "Pokhara / Gairapatan / Gairapatan",
    "Pokhara / Galeshwor / Galeshwor",
    "Pokhara / Gharipatan / Gharipatan",
    "Pokhara / Ghattekhola / Ghattekhola",
    "Pokhara / Ghattey Khola / Ghattey Khola",
    "Pokhara / Ghaticchhina / Ghaticchhina",
    "Pokhara / Halanchowk / Halanchowk",
    "Pokhara / Hamalchowk / Hamal chowk",
    "Pokhara / Hanuman Chowk / Hanuman Chowk",
    "Pokhara / Harichowk / Harichowk",
    "Pokhara / Indra Chowk / Indra Chowk",
    "Pokhara / Jaimure / Jaimure",
    "Pokhara / Jarebar / Jarebar",
    "Pokhara / Kalika Chok / Tallo Phedi",
    "Pokhara / Kalika Chowk / Kalika Chowk",
    "Pokhara / Kalika Than / Kalika Than",
    "Pokhara / Kalikachwok / Kalika chwok",
    "Pokhara / Kande / Kande",
    "Pokhara / Karkitagara / Karkitagara",
    "Pokhara / Kaskikot / Kaskikot",
    "Pokhara / Khahare / Khahare",
    "Pokhara / Kharanefat / Kharanefat",
    "Pokhara / Khudi / Khudi",
    "Pokhara / Lamachaur / Lamachaur",
    "Pokhara / Lamachaur (Pokhara) / Lamachaur (Pokhara)",
    "Pokhara / Lamgadhi / Lamgadhi",
    "Pokhara / Lamo Chautara / Lamo Chautara",
    "Pokhara / Lauruk / Lauruk",
    "Pokhara / Lekhnathchowk / Lekhnath chowk",
    "Pokhara / Lewade / Lewade",
    "Pokhara / Maasbar / Maasbar",
    "Pokhara / Mahakali Chowk / Mahakali Chowk",
    "Pokhara / Mahendra Gufa / Mahendra Gufa",
    "Pokhara / Mahendrapool / Mahendrapool",
    "Pokhara / Malepatan / Malepatan",
    "Pokhara / Manipal / Manipal",
    "Pokhara / Mathilllo Phedi / Mathilo Phedi",
    "Pokhara / Mathilo Phedi / Mathilo Phedi",
    "Pokhara / Matgauda / Matgauda",
    "Pokhara / Methlang / Methlang",
    "Pokhara / Milanchok / Milanchok",
    "Pokhara / Miyapatan / Miyapatan",
    "Pokhara / Mohariya / Mohariya",
    "Pokhara / Myagdi Chowk / Myagdi Chowk",
    "Pokhara / Nadipur / Nadipur",
    "Pokhara / Nagdhunga / Nagdhunga",
    "Pokhara / Naharchwok / Nahar chwok",
    "Pokhara / Naudada / Naudada",
    "Pokhara / Naya Gau / Naya Gau",
    "Pokhara / Newroad / Newroad",
    "Pokhara / Palikhechok / Palikhechok",
    "Pokhara / Pame Bazar / Pame Bazar",
    "Pokhara / Pani Tanki / Pani Tanki",
    "Pokhara / Parsyang / Parsyang",
    "Pokhara / Phedi / Phedi",
    "Pokhara / Pokhara / Kalika Chok",
    "Pokhara / Pokhara / Kalimati",
    "Pokhara / Pokhara / Majuwa",
    "Pokhara / Pokhara / Pokhara",
    "Pokhara / Pokhara Univercity Chwok / Pokhara Univercity Chwok",
    "Pokhara / Pragati Chok / Pragati Chok",
    "Pokhara / Prithvichowk / Prithvichowk",
    "Pokhara / Pu Chwok / Pu Chwok",
    "Pokhara / Rambazar / Rambazar",
    "Pokhara / Ranipauwa / Ranipauwa",
    "Pokhara / Rithepani / Rithepani",
    "Pokhara / Sahare Tara, Purano Buspark / Sahare Tara, Purano Buspark",
    "Pokhara / Sainik Basti / Sainik Basti",
    "Pokhara / Sanito Tol / Sanito Tol",
    "Pokhara / Sapkota Chok / Sapkota Chok",
    "Pokhara / Sarangkot / Sarangkot",
    "Pokhara / Sedi / Sedi",
    "Pokhara / Shanti Chok / Shanti Chok",
    "Pokhara / Silingbot / Silingbot",
    "Pokhara / Simpani / Simpani",
    "Pokhara / Sisuwa / Sisuwa",
    "Pokhara / Suikhet / Suikhet",
    "Pokhara / Sukedada / Sukedada",
    "Pokhara / Sundar Puri / Sundar Puri",
    "Pokhara / Tagakomukh / Tagakomukh",
    "Pokhara / Talchowk / Tal chowk",
    "Pokhara / Tallo Gagangaunda / Tallo Gagangaunda",
    "Pokhara / Tersapatti / Tersapatti",
    "Pokhara / Thuldhunga / Thuldhunga",
    "Pokhara / Tibetian Camp / Tibetian Camp",
    "Pokhara / Tiklang / Tiklang",
    "Pokhara / Toripani / Toripani",
    "Pokhara / Tusli Ghat / Tusli Ghat",
    "Pokhara / Vedipharam / Vedipharam",
    "Pokhara / Ward 18 Area / Ward 18 Area",
    "Pokhara / Yamdi / Yamdi",
    "Pyuthan / Bijuwar (Pyuthan) / Bijuwar (Pyuthan)",
    "Pyuthan / Nayagaun(Pyuthan) / Nayagaun(Pyuthan)",
    "Pyuthan / Pyuthan / Pyuthan",
    "Rajapur (Bardiya) / Rajapur (Bardiya) / Rajapur (Bardiya)",
    "Rajarani(Dhankuta) / Rajarani(Dhankuta) / Rajarani(Dhankuta)",
    "Rajbiraj (Saptari) / Rajbiraj (Saptari) / Rajbiraj (Saptari)",
    "Rajpur Dipayal (Doti) / Rajpur Dipayal (Doti) / Rajpur Dipayal (Doti)",
    "Ramgram (Bhairahawa) / Ramgram (Bhairahawa) / Ramgram (Bhairahawa)",
    "Ramechhap Bazar / Ramechhap Bazar / District Hospital, Ramechhap",
    "Ramechhap Bazar / Ramechhap Bazar / Ramechhap Bazar",
    "Rampur (Palpa) / Rampur (Palpa) / Rampur (Palpa)",
    "Rampur thokshila(Udayapur) / Rampur thokshila(Udayapur) / Rampur thokshila(Udayapur)",
    "Ratnanagar (Chitwan) / 2 No. Road / 2 No. Road",
    "Ratnanagar (Chitwan) / Bachheuli / Bachheuli",
    "Ratnanagar (Chitwan) / Bachauli / Bachauli",
    "Ratnanagar (Chitwan) / Bairahani / Bairahani",
    "Ratnanagar (Chitwan) / Bairiya / Bairiya",
    "Ratnanagar (Chitwan) / Bakulahar / Bakulahar",
    "Ratnanagar (Chitwan) / Belsi / Belsi",
    "Ratnanagar (Chitwan) / Bhaktini Bagaicha / Bhaktini Bagaicha",
    "Ratnanagar (Chitwan) / Bhanu Chowk / Bhanu Chowk",
    "Ratnanagar (Chitwan) / Bhokaha / Bhokaha",
    "Ratnanagar (Chitwan) / Bodhreni / Bodhreni",
    "Ratnanagar (Chitwan) / Chainpur Highway / Chainpur Highway",
    "Ratnanagar (Chitwan) / Chau Chau Factory / Chau Chau Factory",
    "Ratnanagar (Chitwan) / Chitrasari / Chitrasari",
    "Ratnanagar (Chitwan) / Club chowk / Club chowk",
    "Ratnanagar (Chitwan) / Debauli / Debauli",
    "Ratnanagar (Chitwan) / Dobato / Dobato",
    "Ratnanagar (Chitwan) / Dumri Chowk / Dumri Chowk",
    "Ratnanagar (Chitwan) / Gawahi / Gawahi",
    "Ratnanagar (Chitwan) / Gheghauli / Gheghauli",
    "Ratnanagar (Chitwan) / Gunjaman Hospital / Gunjaman Hospital",
    "Ratnanagar (Chitwan) / Harihar Mandir / Harihar Mandir",
    "Ratnanagar (Chitwan) / Harnari-Bairiya / Harnari-Bairiya",
    "Ratnanagar (Chitwan) / High School Road / High School Road",
    "Ratnanagar (Chitwan) / Holiland Area / Holiland Area",
    "Ratnanagar (Chitwan) / Janakauli / Janakauli",
    "Ratnanagar (Chitwan) / Jayamangala / Jayamangala",
    "Ratnanagar (Chitwan) / Jirauna / Jirauna",
    "Ratnanagar (Chitwan) / Jhuwani / Jhuwani",
    "Ratnanagar (Chitwan) / Jutpani / Jutpani",
    "Ratnanagar (Chitwan) / Jyamire / Jyamire",
    "Ratnanagar (Chitwan) / Khairahani Bazar / Khairahani Bazar",
    "Ratnanagar (Chitwan) / Khanal Tol / Khanal Tol",
    "Ratnanagar (Chitwan) / Khurkhure / Khurkhure",
    "Ratnanagar (Chitwan) / Krishna Mandir / Krishna Mandir",
    "Ratnanagar (Chitwan) / Laurighol / Laurighol",
    "Ratnanagar (Chitwan) / Madhavpur / Madhavpur",
    "Ratnanagar (Chitwan) / Mainaha / Mainaha",
    "Ratnanagar (Chitwan) / Nipani / Nipani",
    "Ratnanagar (Chitwan) / Pampa / Pampa",
    "Ratnanagar (Chitwan) / Paradiya Pul / Paradiya Pul",
    "Ratnanagar (Chitwan) / Parsa (Ratnanagar chitwan) / Parsa (Ratnanagar chitwan)",
    "Ratnanagar (Chitwan) / Parsauni / Parsauni",
    "Ratnanagar (Chitwan) / Pithuwa / Pithuwa",
    "Ratnanagar (Chitwan) / Ratnanagar (Chitwan) / Ratnanagar (Chitwan)",
    "Ratnanagar (Chitwan) / Salghari / Salghari",
    "Ratnanagar (Chitwan) / Sauraha / Sauraha",
    "Ratnanagar (Chitwan) / Seri / Seri",
    "Ratnanagar (Chitwan) / Simal Tandi / Simal Tandi",
    "Ratnanagar (Chitwan) / Subba Chowk / Subba Chowk",
    "Ratnanagar (Chitwan) / Suryapur / Suryapur",
    "Ratnanagar (Chitwan) / Tarauli / Tarauli",
    "Ratnanagar (Chitwan) / Tarkari Chowk / Tarkari Chowk",
    "Ratnanagar (Chitwan) / Tikauli / Tikauli",
    "Ratuwamai (Sombare) / Ratuwamai (Sombare) / Ratuwamai (Sombare)",
    "Rautahat / Rautahat / Rautahat",
    "Rukumkot / Rukumkot / Rukumkot",
    "Rupani (Saptari) / Nepaltar (Illam) / Nepaltar (Illam)",
    "Rupani (Saptari) / Rupani (Saptari) / Rupani (Saptari)",
    "Rupnagar (Saptari) / Rupnagar (Saptari) / Rupnagar (Saptari)",
    "Sainamaina (Rupandehi) / Sainamaina (Rupandehi) / Sainamaina (Rupandehi)",
    "Salleri (Solukhumbu) / Salleri (Solukhumbu) / Salleri (Solukhumbu)",
    "Samsherpur (Bardiya) / Samsherpur (Bardiya) / Chandeshwoi Temple",
    "Samsherpur (Bardiya) / Samsherpur (Bardiya) / Samsherpur (Bardiya)",
    "Samsherpur (Bardiya) / Samsherpur (Bardiya) / Tokha Mandir",
    "Sanga (Banepa) / Sanga (Banepa) / Sanga (Banepa)",
    "Shahilek (Baitadi) / Shailekh (Baitadi) / Shailekh (Baitadi)",
    "Shuklagandaki (Tanhau) / Shuklagandaki (Tanhau) / Shuklagandaki (Tanhau)",
    "Sidhuwa (Hile) / Sidhuwa (Hile) / Sidhuwa (Hile)",
    "Simara (Bara) / Simara (Bara) / Simara (Bara)",
    "Simikot (Humla) / Simikot (Humla) / Simikot (Humla)",
    "Sindhuli Bazar / Sindhuli Bazar / Sindhuli Bazar",
    "Siraha Bazar / Siraha Bazar / Siraha Bazar",
    "Sudal (Bhaktapur) / Sudal (Bhaktapur) / Sudal (Bhaktapur)",
    "Sulichaur (Rolpa) / Sulichaur (Rolpa) / Sulichaur (Rolpa)",
    "Sunwal / Sunwal / Sunwal",
    "Surkhet / Bangesimal (Surkhet) / Bangesimal (Surkhet)",
    "Surkhet / Ramghat (Surkhet) / Ramghat (Surkhet)",
    "Surkhet / Surkhet / Surkhet",
    "Syangja / Bayarghari (Syangja) / Bayarghari (Syangja)",
    "Syangja / Jugle (Syangja) / Jugle (Syangja)",
    "Syangja / Mirmiphat (Syangja) / Mirmiphat (Syangja)",
    "Syangja / Phedikhola (Syangja) / Phedikhola (Syangja)",
    "Syangja / Putalibazaar (Syangja) / Putalibazaar (Syangja)",
    "Syangja / Syangja / Raniswara",
    "Syangja / Syangja / Syangja",
    "Syangja / Syanja / Syanja",
    "Tamaghat / Tamaghat / Tamaghat",
    "Tandi (Chitwan) / Tandi (Chitwan) / Tandi (Chitwan)",
    "Tansen (Palpa) / Tansen (Palpa) / Tansen (Palpa)",
    "Taplejung Bazar / Taplejung Bazar / Taplejung Bazar",
    "Taplejung Bazar / Taplejung Bazar / Taplejung Bus Station",
    "Taplejung Bazar / Taplejung Bazar / Pathivara Mandir",
    "Tarahara (Sunsari) / Tarahara(Sunsari) / Tarahar (Sunsari)",
    "Tatopani (Sindhupalchowk) / Tatopani (Sindhupalchowk) / Tatopani (Sindhupalchowk)",
    "Taulihawa (Kapilvastu) / Taulihawa (Kapilvastu) / Taulihawa (Kapilvastu)",
    "Tehrathum Bazar / Tehrathum Bazar / Tehrathum Bazar",
    "Thutipipal (Bhairahawa) / Thutipipal (Bhairahawa) / Thutipipal (Bhairahawa)",
    "Tikapur (Kailali) / Tikapur (Kailali) / Tikapur (Kailali)",
    "Tilottama (Lumbini) / Tilottma (Lumbini) / Tilottma (Lumbini)",
    "Tulsipur (Dang) / Tulsipur (Dang) / Tulsipur (Dang)",
    "Tumlingtar (Sankhuwasabha) / Tumlingtar (Sankhuwasabha) / Tumlingtar (Sankhuwasabha)",
    "Udayapur / Belsot (Katari) / Belsot (Katari)",
    "Udayapur / Nepaltar (Udayapur) / Nepaltar (Udayapur)",
    "Waling (Syangja) / Waling / Waling"
];
